#=========================== Filebeat inputs =============================

filebeat.inputs:

# Each - is an input. Most options can be set at the input level, so
# you can use different inputs for various configurations.
# Below are the input specific configurations.

  - type: log
    # Change to true to enable this input configuration.
    enabled: true

    # Paths that should be crawled and fetched. Glob based paths.
    paths:
      - /usr/local/tomcat/logs/catalina.*.log

    fields:
      docker_type: tomcat
      log_type: catalina

    ### Multiline options

    # Multiline can be used for log messages spanning multiple lines. This is common
    # for Java Stack Traces or C-Line Continuation

    # The regexp Pattern that has to be matched. The example pattern matches all lines starting with [
    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'

    # Defines if the pattern set under pattern should be negated or not. Default is false.
    multiline.negate: false

    # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
    # that was (not) matched before or after or as long as a pattern is not matched based on negate.
    # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
    multiline.match: after

  - type: log
    enabled: true
    paths:
      - /usr/local/tomcat/logs/localhost_access_log.*.txt
    fields:
      docker_type: tomcat
      log_type: localhost_access_log
    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'
    multiline.negate: false
    multiline.match: after

  - type: log
    enabled: true
    paths:
      - /usr/local/tomcat/logs/manager.*.txt
    fields:
      docker_type: tomcat
      log_type: manager
    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'
    multiline.negate: false
    multiline.match: after

  - type: log
    enabled: true
    paths:
      - /usr/local/tomcat/logs/host-manager.*.txt
    fields:
      docker_type: tomcat
      log_type: manager
    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'
    multiline.negate: false
    multiline.match: after

  - type: log
    enabled: true
    paths:
      - /usr/local/tomcat/logs/localhost.*.txt
    fields:
      docker_type: tomcat
      log_type: localhost
    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'
    multiline.negate: false
    multiline.match: after

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
name: "kheops_dicom_web_proxy"

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: [${elastic_tags}]

# Optional fields that you can specify to add additional information to the
# output.
fields:
  instance: ${instance}

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#--------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["${logstash_url}"]

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
