language: minimal
sudo: required

services:
  - docker

notifications:
  email: false

before_install:
  - git fetch --unshallow

script:
  - docker build --target build -t build .
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t osirixfoundation/kheops-dicomweb-proxy:$TRAVIS_BRANCH .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push osirixfoundation/kheops-dicomweb-proxy:$TRAVIS_BRANCH

deploy:
  provider: script
  script: docker run --rm build gradle sonarqube -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN --no-daemon
  skip_cleanup: true
  on:
    branch: master
