sudo: required

services:
  - docker

notifications:
  email: false

before_script:
   - export BRANCH=$TRAVIS_BRANCH

script:
   - ./build
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker push osirixfoundation/pacs-authorization-proxy:$BRANCH
