#language: minimal

#node_js:
#  - "lts/*"

services:
  - docker

notifications:
  email: false

#before_script:
#  - npm -v
#  - node -v
#  - npm install jquery@1.9.1 --save
#  - npm install

script:
#  - export BUILD_DIR=$TRAVIS_BUILD_DIR/dist
#  - export BRANCH=$TRAVIS_BRANCH
#  - npm run build > output.txt
#  - cp -r $BUILD_DIR $TRAVIS_BUILD_DIR/docker/dist
#  - cp -r $BUILD_DIR $TRAVIS_BUILD_DIR/docker/tls/dist
#  - cp -r $TRAVIS_BUILD_DIR/src/assets $TRAVIS_BUILD_DIR/docker/assets
#  - cp -r $TRAVIS_BUILD_DIR/src/assets $TRAVIS_BUILD_DIR/docker/tls/assets
   - docker build -t osirixfoundation/kheops-ui:$TRAVIS_BRANCH .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker push osirixfoundation/kheops-ui:$TRAVIS_BRANCH

#after_success:
#  - cd $TRAVIS_BUILD_DIR
#  - chmod +x docker/deploy_no_tls.sh
#  - chmod +x docker/tls/deploy_tls.sh

#deploy:
#  skip_cleanup: true
#  provider: script
#  script:
#    ./docker/deploy_no_tls.sh;
#    ./docker/tls/deploy_tls.sh
#  on:
#    all_branches: true
