language: minimal
sudo: required

notifications:
  email: false

before_install:
  - git fetch --unshallow

script:
  - docker build --target build -t build .
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t osirixfoundation/kheops-dicomweb-proxy:$TRAVIS_BRANCH .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push osirixfoundation/kheops-dicomweb-proxy:$TRAVIS_BRANCH

deploy:
  provider: script
  script: echo "org $SONAR_ORGANIZATION" && docker run --rm build gradle sonarqube "-Dsonar.organization=$SONAR_ORGANIZATION" -Dsonar.host.url=https://sonarcloud.io "-Dsonar.login=$SONAR_LOGIN" --scan --info --stacktrace --no-daemon
  skip_cleanup: true
  on:
    branch: master
