language: java
sudo: required

services:
  - docker
  
notifications:
  email: false
  
after_success:
  - chmod +x docker/docker_push.sh
  - export BRANCH=$TRAVIS_BRANCH
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$BRANCH"

deploy:
  skip_cleanup: true
  provider: script
  script: docker/docker_push.sh 
  on:
    all_branches: true
