language: java
sudo: required

services:
  - docker
  
after_success:
  - docker build ./docker/ -t osirixfoundation/test
  
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
 
