language: java
sudo: required

services:
  - docker
  
notifications:
  email: false
  
after_success:
  - chmod +x docker/docker_push.sh

deploy:
  skip_cleanup: true
  provider: script
  script: docker/docker_push.sh 
