language: java
sudo: required

services:
  - docker
  
notifications:
  email: false
  
after_success:
  - chmod +x docker/docker_push.sh
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: docker/docker_push.sh 
