version: "3.1"

services:
    proxy:
        container_name: proxy
        image: osirixfoundation/pacsproxyauthorization:latest
        ports:
            - "80:80"
    backend:
        container_name: backend
        image: backend-image
        
