#============================= Filebeat inputs ================================

filebeat.inputs:

  - type: log
    enabled: true
    paths:
      - /kheops/authorization/logs/catalina.*.log

    fields:
      docker_type: tomcat
      log_type: catalina

    ### Multiline options

    # The regexp Pattern that has to be matched. The example pattern matches all lines starting with [
    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'

    # Defines if the pattern set under pattern should be negated or not. Default is false.
    multiline.negate: false

    # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
    # that was (not) matched before or after or as long as a pattern is not matched based on negate.
    # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
    multiline.match: after

  - type: log
    enabled: true
    paths:
      - /kheops/authorization/logs/localhost_access_log.*.txt

    exclude_lines: ['.*/authorization/metrics.*']

    fields:
      docker_type: tomcat
      log_type: localhost_access_log

    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'
    multiline.negate: false
    multiline.match: after

  - type: log
    enabled: true
    paths:
      - /kheops/authorization/logs/manager.*.txt

    fields:
      docker_type: tomcat
      log_type: manager

    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'
    multiline.negate: false
    multiline.match: after

  - type: log
    enabled: true
    paths:
      - /kheops/authorization/logs/host-manager.*.txt

    fields:
      docker_type: tomcat
      log_type: manager

    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'
    multiline.negate: false
    multiline.match: after

  - type: log
    enabled: true
    paths:
      - /kheops/authorization/logs/localhost.*.txt

    fields:
      docker_type: tomcat
      log_type: localhost

    multiline.pattern: '^\t|^[[:space:]]+(at|...)|^Caused by:|^Suppressed:'
    multiline.negate: false
    multiline.match: after

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
name: "kheops_authorization"

# Optional fields that you can specify to add additional information to the
# output.
fields:
  instance: ${instance}

#================================ Outputs =====================================

#--------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["${logstash_url}"]
