name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.4
      with:
        name: osirixfoundation/kheops-reverse-proxy
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}     
