name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: webhook
       uses: zzzze/webhook-trigger@master
       with:
         data: "{\"request\":{\"branch\":\"ci-test\",\"message\":\"from github\"}}"
         webhook_url: "https://api.travis-ci.com/repo/19160020/requests"
         options: "-H \"Content-Type: application/json\" -H \"Accept: application/json\" -H \"Travis-API-Version: 3\" -H \"Authorization: token ${{ secrets.TRAVIS_TOKEN }}\""
