name: Docker Image CI

on: [push]

jobs:
  build_ci-test:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Extract branch name
        if: startsWith(github.ref , 'refs/heads/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Extract branch tag
        if: startsWith(github.ref , 'refs/tags/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ci-test/Dockerfile
          platforms: linux/amd64
          push: true
          tags: osirixfoundation/kheops-reverse-proxy:${{ env.docker_tag }}-ci-test

  build_insecure:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Extract branch name
        if: startsWith(github.ref , 'refs/heads/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Extract branch tag
        if: startsWith(github.ref , 'refs/tags/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: insecure/Dockerfile
          platforms: linux/amd64
          push: true
          tags: osirixfoundation/kheops-reverse-proxy:${{ env.docker_tag }}-insecure

          
  build_secure:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Extract branch name
        if: startsWith(github.ref , 'refs/heads/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Extract branch tag
        if: startsWith(github.ref , 'refs/tags/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: secure/Dockerfile
          platforms: linux/amd64
          push: true
          tags: osirixfoundation/kheops-reverse-proxy:${{ env.docker_tag }}-secure
        
        
  build_letsencrypt:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Extract branch name
        if: startsWith(github.ref , 'refs/heads/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Extract branch tag
        if: startsWith(github.ref , 'refs/tags/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: letsencrypt/Dockerfile
          platforms: linux/amd64
          push: true
          tags: osirixfoundation/kheops-reverse-proxy:${{ env.docker_tag }}-letsencrypt