name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Extract branch name
        if: startsWith(github.ref , 'refs/heads/')
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
               
      - name: Extract tag name
        if: startsWith(github.ref , 'refs/tags/')
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
        
      - name: Build and push by branch
        if: startsWith(github.ref , 'refs/heads/')
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: osirixfoundation/kheops-filebeat-sidecar:${{ steps.extract_branch.outputs.branch }}   
  
      - name: Build and push by tag
        if: startsWith(github.ref , 'refs/tags/')
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: osirixfoundation/kheops-filebeat-sidecar:${{ steps.extract_tag.outputs.tag }}
