name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
              
      #- name: build with script
       # shell: bash
       # run: ./build
        #env:
         # BRANCH: ${{ steps.extract_branch.outputs.branch }}
          
          
      - name: Push
        uses: docker/build-push-action@v2.2.1
        with:
          context: hosts/proxy
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: osirixfoundation/pacs-authorization-proxy:${{ steps.extract_branch.outputs.branch }}
